after_success: npm run coveralls

before_install:
  - nvm install 8
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install -g lerna@2.4.0

cache:
  yarn: true

install:
  - yarn

jdk:
  - oraclejdk8

language: java

script: 
  - npm run build
  - npm run checkFormat
  - npm run lint
  - npm run jest