after_success: npm run coveralls

before_install:
  - nvm install 8
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install -g lerna@3.4.0

branches:
  except:
  - wedeploy

cache:
  yarn: true

install:
  - yarn

dist: trusty

jdk:
  - oraclejdk8

language: java

script:
  - npm run testSoy
  - npm run checkFormat
  - npm run lint
  - npm run soy
  - npm run jest