before_install:
  - nvm install 8
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.2
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install -g lerna@2.0.0-rc.5

cache:
  yarn: true

install:
  - npm run lerna

jdk:
  - oraclejdk8

language: java

script: npm run ci
